"""
``predict.py`` for a text-classification run: a standalone scorer shipped in the run directory.

The script imports nothing from ``mb``; it needs only numpy and the backend's own libraries.
Its backend-specific loader comes from the backend class
(:meth:`~mb.models.text_backends.base.TextBackend.standalone_source`), and the shared part
here applies ``calibrator.json`` and the decision threshold from ``thresholds.json``. Both are
read at run time, so the script stays valid after ``mb text evaluate`` rewrites them. Like the
model card it is a run artifact, so its messages are fixed English.
"""

from __future__ import annotations

from pathlib import Path
from typing import Type

from mb.evaluate.classification.text_evaluation import CALIBRATOR_FILE, MODEL_DIR, THRESHOLDS_FILE
from mb.models.text_backends.base import BACKEND_META_FILE, TextBackend

PREDICT_SCRIPT_FILE = "predict.py"

_HEADER = '''#!/usr/bin/env python3
"""
Standalone scorer for this text-classification run (backend: __BACKEND__).

Generated by Model Builder (`mb`); it does not import `mb`. Keep it in the run directory:
it reads __MODEL_DIR__/, __CALIBRATOR_FILE__ and __THRESHOLDS_FILE__ next to itself.
Requires: __REQUIREMENTS__.

Command line (prints text<TAB>score<TAB>flagged with a header):
    python predict.py "first string" "second string"
    python predict.py --input lines.txt --output scores.tsv   # one string per line

Python:
    from predict import load
    clf = load()                       # or load("path/to/run", device="cpu")
    clf.score(["some string"])         # calibrated p(label = 1), numpy array
    clf.flag(["some string"])          # score >= decision threshold

Scores match `mb text score` up to floating-point differences between devices.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import numpy as np

BACKEND = __BACKEND_REPR__
RUN_DIR = Path(__file__).resolve().parent
_EPS = 1e-7


def _sigmoid(x):
    return 0.5 * (1.0 + np.tanh(0.5 * np.asarray(x, dtype=np.float64)))


def _logit(p):
    p = np.clip(np.asarray(p, dtype=np.float64), _EPS, 1.0 - _EPS)
    return np.log(p) - np.log1p(-p)


def _auto_device(device):
    if device:
        return device
    import torch

    return "cuda" if torch.cuda.is_available() else "cpu"


def _calibrate(params, probs):
    method = params.get("method")
    if method == "temperature":
        return _sigmoid(_logit(probs) / float(params["temperature"]))
    if method == "platt":
        return _sigmoid(float(params["a"]) * _logit(probs) + float(params["b"]))
    if method == "isotonic":
        return np.interp(np.asarray(probs, dtype=np.float64), params["x"], params["y"])
    raise ValueError(f"Unknown calibration method: {method!r}")


def _read_json(path):
    return json.loads(Path(path).read_text(encoding="utf-8"))
'''

_FOOTER = '''

class TextClassifier:
    """This run's model with its calibration and decision threshold applied."""

    def __init__(self, run_dir=RUN_DIR, device=None):
        run_dir = Path(run_dir)
        model_dir = run_dir / __MODEL_DIR__
        meta = _read_json(model_dir / __BACKEND_META_FILE__)
        if meta.get("backend") != BACKEND:
            raise ValueError(f"{model_dir} holds a {meta.get('backend')!r} model; this script loads {BACKEND!r}")
        self.model = load_model(model_dir, meta, device)
        self.calibration = _read_json(run_dir / __CALIBRATOR_FILE__)
        self.threshold = float(_read_json(run_dir / __THRESHOLDS_FILE__)["decision"]["threshold"])

    def score(self, texts):
        """Calibrated p(label = 1) per text, in input order."""
        texts = list(texts)
        if not texts:
            return np.empty(0, dtype=np.float64)
        return _calibrate(self.calibration, self.model.predict_proba(texts))

    def flag(self, texts, threshold=None):
        """``score >= threshold`` (default: the run's decision threshold)."""
        return self.score(texts) >= (self.threshold if threshold is None else threshold)


def load(run_dir=RUN_DIR, device=None):
    return TextClassifier(run_dir, device)


def _read_lines(path):
    with open(path, "r", encoding="utf-8", newline="\\n") as f:
        return [_strip_line_end(line) for line in f]


def _strip_line_end(line):
    if line.endswith("\\n"):
        line = line[:-1]
    if line.endswith("\\r"):
        line = line[:-1]
    return line


def main(argv=None):
    parser = argparse.ArgumentParser(description=f"Score strings with this {BACKEND} run.")
    parser.add_argument("texts", nargs="*", help="Strings to score")
    parser.add_argument("--input", help="UTF-8 file, one string per line (scored after any positional strings)")
    parser.add_argument("--output", help="Output TSV path (default: stdout)")
    parser.add_argument("--device", help="e.g. cuda or cpu (default: cuda when available)")
    parser.add_argument("--threshold", type=float, help="Override the decision threshold")
    args = parser.parse_args(argv)
    texts = list(args.texts) + (_read_lines(args.input) if args.input else [])
    if not texts:
        parser.error("give strings to score or --input")
    clf = load(device=args.device)
    threshold = clf.threshold if args.threshold is None else args.threshold
    scores = clf.score(texts)
    if args.output:
        out = open(args.output, "w", encoding="utf-8", newline="\\n")
    else:
        out = sys.stdout
        # Strings can hold characters a console's legacy code page cannot encode.
        out.reconfigure(encoding="utf-8")
    try:
        out.write("text\\tscore\\tflagged\\n")
        for text, s in zip(texts, scores):
            out.write(f"{text}\\t{s:.6f}\\t{int(s >= threshold)}\\n")
    finally:
        if out is not sys.stdout:
            out.close()
    return 0


if __name__ == "__main__":
    sys.exit(main())
'''


def predict_script_source(backend_cls: Type[TextBackend]) -> str:
    """The complete ``predict.py`` for a run of *backend_cls*."""
    values = {
        "__BACKEND_REPR__": repr(backend_cls.name.value),
        "__BACKEND__": backend_cls.name.value,
        "__MODEL_DIR__": MODEL_DIR,
        "__CALIBRATOR_FILE__": CALIBRATOR_FILE,
        "__THRESHOLDS_FILE__": THRESHOLDS_FILE,
        "__REQUIREMENTS__": ", ".join(("numpy",) + tuple(backend_cls.standalone_requirements)),
    }
    header = _HEADER
    for key, value in values.items():
        header = header.replace(key, value)
    footer = _FOOTER
    for key, value in (
        ("__MODEL_DIR__", MODEL_DIR),
        ("__BACKEND_META_FILE__", BACKEND_META_FILE),
        ("__CALIBRATOR_FILE__", CALIBRATOR_FILE),
        ("__THRESHOLDS_FILE__", THRESHOLDS_FILE),
    ):
        footer = footer.replace(key, repr(value))
    return header + "\n" + backend_cls.standalone_source() + footer


def write_predict_script(run_dir: Path, backend_cls: Type[TextBackend]) -> Path:
    path = Path(run_dir) / PREDICT_SCRIPT_FILE
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(predict_script_source(backend_cls))
    return path
