"""Bundle export: safetensors weights + manifest (+ optional architecture stub)."""

from __future__ import annotations

import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Optional

from mb.conversion.converters import convert_pytorch_to_safetensors, detect_model_framework


def _sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def _discover_class_names(data_dir: Optional[Path]) -> list[str]:
    if data_dir is None:
        return []
    train_dir = Path(data_dir) / "train"
    if not train_dir.is_dir():
        return []
    return sorted([p.name for p in train_dir.iterdir() if p.is_dir()])


def _architecture_stub_text(
    *,
    architecture: Optional[str],
    num_classes: Optional[int],
    framework: str,
) -> str:
    arch = architecture or "resnet34"
    ncls = int(num_classes) if num_classes is not None else 2
    return f"""# Auto-generated by `mb export bundle`
from __future__ import annotations

import torch
from torchvision import models


def build_model(num_classes: int = {ncls}):
    # Replace mapping below if using a non-resnet torchvision architecture.
    architecture = "{arch}"
    if architecture == "resnet18":
        m = models.resnet18(weights=None)
    elif architecture == "resnet34":
        m = models.resnet34(weights=None)
    elif architecture == "resnet50":
        m = models.resnet50(weights=None)
    elif architecture == "resnet101":
        m = models.resnet101(weights=None)
    elif architecture == "resnet152":
        m = models.resnet152(weights=None)
    else:
        raise ValueError(f"Unsupported stub architecture: {{architecture}}")
    m.fc = torch.nn.Linear(m.fc.in_features, num_classes)
    return m


if __name__ == "__main__":
    print("framework={framework}, architecture={arch}, num_classes={ncls}")
"""


def export_bundle(
    *,
    input_model: Path,
    output_dir: Path,
    architecture: Optional[str],
    num_classes: Optional[int],
    class_names: Optional[list[str]],
    data_dir: Optional[Path],
    image_size: int,
    include_architecture_py: bool,
    run_id: Optional[str] = None,
) -> dict[str, Any]:
    """
    Export a model bundle as ``model.safetensors`` + ``model_manifest.json``.
    Returns a small result payload with written file paths.
    """
    source_fw = detect_model_framework(input_model)
    if source_fw != "pytorch":
        raise ValueError("mb export bundle currently supports PyTorch (.pth/.pt) input only")

    output_dir.mkdir(parents=True, exist_ok=True)
    weights_path = output_dir / "model.safetensors"
    manifest_path = output_dir / "model_manifest.json"
    arch_py_path = output_dir / "model_architecture.py"

    ok = convert_pytorch_to_safetensors(input_model, weights_path)
    if not ok or not weights_path.exists():
        raise RuntimeError("Failed to export safetensors weights")

    resolved_classes = list(class_names or [])
    if not resolved_classes:
        resolved_classes = _discover_class_names(data_dir)
    resolved_num_classes = int(num_classes) if num_classes is not None else None
    if resolved_num_classes is None and resolved_classes:
        resolved_num_classes = len(resolved_classes)

    manifest = {
        "schema_version": 1,
        "created_at": datetime.now(timezone.utc).isoformat(),
        "export": {"command": "mb export bundle", "run_id": run_id},
        "model": {
            "framework": "pytorch",
            "weights_format": "safetensors",
            "architecture": architecture,
            "num_classes": resolved_num_classes,
            "class_names": resolved_classes or None,
        },
        "preprocessing": {
            "image_size": int(image_size),
            "channels": 3,
            "normalize_mean": [0.485, 0.456, 0.406],
            "normalize_std": [0.229, 0.224, 0.225],
        },
        "artifacts": {
            "weights_file": weights_path.name,
            "weights_sha256": _sha256_file(weights_path),
            "weights_size_bytes": weights_path.stat().st_size,
            "architecture_file": arch_py_path.name if include_architecture_py else None,
        },
    }
    manifest_path.write_text(json.dumps(manifest, indent=2), encoding="utf-8")

    if include_architecture_py:
        arch_py_path.write_text(
            _architecture_stub_text(
                architecture=architecture,
                num_classes=resolved_num_classes,
                framework="pytorch",
            ),
            encoding="utf-8",
        )

    return {
        "weights_path": str(weights_path),
        "manifest_path": str(manifest_path),
        "architecture_path": str(arch_py_path) if include_architecture_py else None,
    }

