"""Bundle export: safetensors weights + manifest (+ optional architecture stub)."""

from __future__ import annotations

import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Optional

from mb.conversion.converters import convert_pytorch_to_safetensors, detect_model_framework
from mb.utils.snapshot import UnifiedSnapshot, find_unified_snapshot


def _sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def _discover_class_names(data_dir: Optional[Path]) -> list[str]:
    if data_dir is None:
        return []
    train_dir = Path(data_dir) / "train"
    if not train_dir.is_dir():
        return []
    return sorted([p.name for p in train_dir.iterdir() if p.is_dir()])


def _discover_class_names_from_snapshot(snapshot: Any) -> list[str]:
    images = getattr(snapshot, "images", None)
    if not isinstance(images, dict):
        return []
    names: set[str] = set()
    for rec in images.values():
        if not isinstance(rec, dict):
            continue
        for key in ("training", "dataset", "converted"):
            section = rec.get(key)
            if isinstance(section, dict):
                cls = section.get("class")
                if isinstance(cls, str) and cls.strip():
                    names.add(cls.strip())
    return sorted(names)


def _snapshot_summary(snapshot: Any) -> dict[str, Any]:
    try:
        payload = snapshot.to_dict()
    except Exception:
        payload = {}
    if not isinstance(payload, dict):
        payload = {}
    out: dict[str, Any] = {}
    run_id = getattr(snapshot, "run_id", None)
    if isinstance(run_id, str) and run_id.strip():
        out["run_id"] = run_id
    summary = payload.get("summary")
    if isinstance(summary, dict):
        out["summary"] = summary
    raw_dir = payload.get("raw_data_directory")
    if isinstance(raw_dir, str) and raw_dir.strip():
        out["raw_data_directory"] = raw_dir
    data_dir = payload.get("data_directory")
    if isinstance(data_dir, str) and data_dir.strip():
        out["data_directory"] = data_dir
    return out


def _architecture_stub_text(
    *,
    architecture: Optional[str],
    num_classes: Optional[int],
    framework: str,
) -> str:
    arch = architecture or "resnet34"
    ncls = int(num_classes) if num_classes is not None else 2
    return f"""# Auto-generated by `mb export bundle`
from __future__ import annotations

import sys
import torch
import torch.nn as nn
from torchvision import models


class AdaptiveConcatPool2d(nn.Module):
    # FastAI-style adaptive concat pool; included for compatibility/debugging.

    def __init__(self, sz=None):
        super().__init__()
        self.ap = nn.AdaptiveAvgPool2d(sz or 1)
        self.mp = nn.AdaptiveMaxPool2d(sz or 1)

    def forward(self, x):
        return torch.cat([self.mp(x), self.ap(x)], 1)


if "__main__" in sys.modules:
    main_module = sys.modules["__main__"]
    if not hasattr(main_module, "AdaptiveConcatPool2d"):
        setattr(main_module, "AdaptiveConcatPool2d", AdaptiveConcatPool2d)
    if not hasattr(main_module, "AdaptiveConcatPool"):
        setattr(main_module, "AdaptiveConcatPool", AdaptiveConcatPool2d)


def _make_torchvision_backbone(architecture: str):
    # Version-safe torchvision constructor (supports old/new API).
    if not hasattr(models, architecture):
        raise ValueError(f"Unsupported torchvision architecture: {{architecture}}")
    ctor = getattr(models, architecture)
    try:
        return ctor(weights=None)
    except TypeError:
        # Older torchvision signatures used pretrained=False.
        return ctor(pretrained=False)


class ExportedImageModel(nn.Module):
    # Generic wrapper that can represent torchvision-style and FastAI-style layouts.
    def __init__(
        self,
        architecture: str = "{arch}",
        num_classes: int = {ncls},
        *,
        layout: str = "torchvision",
    ):
        super().__init__()
        self.architecture = architecture
        self.num_classes = num_classes
        self.layout = layout
        self.inner = self._build_inner(architecture, num_classes, layout)

    @staticmethod
    def _build_inner(architecture: str, num_classes: int, layout: str) -> nn.Module:
        base = _make_torchvision_backbone(architecture)
        arch_l = str(architecture).lower()
        if layout == "fastai_sequential":
            if not arch_l.startswith("resnet"):
                raise ValueError("fastai_sequential layout currently supports resnet* only")
            backbone = nn.Sequential(*list(base.children())[:-2])
            classifier = nn.Sequential(
                AdaptiveConcatPool2d(),
                nn.Flatten(start_dim=1, end_dim=-1),
                nn.BatchNorm1d(1024),
                nn.Dropout(p=0.25, inplace=False),
                nn.Linear(1024, 512, bias=True),
                nn.ReLU(inplace=True),
                nn.BatchNorm1d(512),
                nn.Dropout(p=0.5, inplace=False),
                nn.Linear(512, num_classes, bias=True),
            )
            return nn.Sequential(backbone, classifier)

        # Default: keep torchvision module layout so keys like layer1.*, fc.* match directly.
        if hasattr(base, "fc") and isinstance(getattr(base, "fc"), nn.Module):
            in_f = base.fc.in_features
            base.fc = nn.Linear(in_f, num_classes)
            return base
        if hasattr(base, "classifier"):
            classifier = getattr(base, "classifier")
            if isinstance(classifier, nn.Sequential) and len(classifier) > 0:
                last_idx = len(classifier) - 1
                last = classifier[last_idx]
                if hasattr(last, "in_features"):
                    classifier[last_idx] = nn.Linear(last.in_features, num_classes)
                else:
                    raise ValueError("Unsupported classifier layout")
                return base
            if hasattr(classifier, "in_features"):
                setattr(base, "classifier", nn.Linear(classifier.in_features, num_classes))
                return base
            raise ValueError("Unsupported classifier layout")
        raise ValueError("Unsupported model head layout for generated stub")

    def forward(self, x):
        return self.inner(x)

    def state_dict(self, *args, **kwargs):
        # Expose inner keys directly (conv1/layer*/fc OR 0./1. layout).
        return self.inner.state_dict(*args, **kwargs)

    def load_state_dict(self, state_dict, strict: bool = True):
        # Load directly into inner model so key spaces match as expected.
        return self.inner.load_state_dict(state_dict, strict=strict)


def build_model(
    num_classes: int = {ncls},
    architecture: str = "{arch}",
    *,
    layout: str = "torchvision",
):
    # Build model through the clean wrapper class.
    return ExportedImageModel(
        architecture=architecture,
        num_classes=num_classes,
        layout=layout,
    )


def infer_layout_from_state_dict(state_dict) -> str:
    keys = list(state_dict.keys())
    if not keys:
        return "torchvision"
    # FastAI-style sequential exports often use 0.* / 1.* top-level keys.
    if any(k.startswith("0.") or k.startswith("1.") for k in keys):
        return "fastai_sequential"
    # torchvision training exports from ModelBuilder use layer*/conv1/fc style.
    return "torchvision"


def load_bundle_model(
    safetensors_path: str,
    *,
    architecture: str = "{arch}",
    num_classes: int = {ncls},
    device: str = "auto",
    strict: bool = False,
    layout: str = "auto",
):
    # Load exported SafeTensors into the generated architecture.
    import safetensors.torch

    if device == "auto":
        dev = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    else:
        dev = torch.device(device)

    state_dict = safetensors.torch.load_file(safetensors_path, device="cpu")
    if layout == "auto":
        layout = infer_layout_from_state_dict(state_dict)
    model = build_model(num_classes=num_classes, architecture=architecture, layout=layout)
    missing, unexpected = model.load_state_dict(state_dict, strict=strict)
    model = model.to(dev)
    model.eval()

    print(f"Loaded on {{dev}} | layout={{layout}} | params={{sum(p.numel() for p in model.parameters()):,}}")
    if missing:
        print(f"Missing keys ({{len(missing)}}): {{missing[:10]}}")
    if unexpected:
        print(f"Unexpected keys ({{len(unexpected)}}): {{unexpected[:10]}}")
    if not missing and not unexpected:
        print("Exact key match.")
    return model, missing, unexpected


def print_version_info():
    import torchvision

    print("=" * 60)
    print("Version Information")
    print("=" * 60)
    print(f"Torch: {{torch.__version__}}")
    print(f"Torchvision: {{torchvision.__version__}}")
    print(f"CUDA Available: {{torch.cuda.is_available()}}")
    print("=" * 60)


if __name__ == "__main__":
    print("framework={framework}, architecture={arch}, num_classes={ncls}")
    print_version_info()
    m = build_model(num_classes={ncls}, architecture="{arch}")
    print(f"Model type: {{type(m).__name__}}")
"""


def export_bundle(
    *,
    input_model: Path,
    output_dir: Path,
    architecture: Optional[str],
    num_classes: Optional[int],
    class_names: Optional[list[str]],
    data_dir: Optional[Path],
    image_size: Optional[int],
    include_architecture_py: bool,
    pipeline_config: Optional[dict[str, Any]] = None,
    snapshot_path: Optional[Path] = None,
    run_id: Optional[str] = None,
) -> dict[str, Any]:
    """
    Export a model bundle as ``model.safetensors`` + ``model_manifest.json``.
    Returns a small result payload with written file paths.
    """
    source_fw = detect_model_framework(input_model)
    if source_fw != "pytorch":
        raise ValueError("mb export bundle currently supports PyTorch (.pth/.pt) input only")

    output_dir.mkdir(parents=True, exist_ok=True)
    weights_path = output_dir / "model.safetensors"
    manifest_path = output_dir / "model_manifest.json"
    arch_py_path = output_dir / "model_architecture.py"

    ok = convert_pytorch_to_safetensors(input_model, weights_path)
    if not ok or not weights_path.exists():
        raise RuntimeError("Failed to export safetensors weights")

    model_cfg = (pipeline_config or {}).get("model") if isinstance(pipeline_config, dict) else None
    data_cfg = (pipeline_config or {}).get("data") if isinstance(pipeline_config, dict) else None
    if not isinstance(model_cfg, dict):
        model_cfg = {}
    if not isinstance(data_cfg, dict):
        data_cfg = {}

    resolved_architecture = architecture or model_cfg.get("default_architecture")
    resolved_data_dir = data_dir
    if resolved_data_dir is None:
        dd = data_cfg.get("data_dir")
        if isinstance(dd, str) and dd.strip():
            resolved_data_dir = Path(dd)

    snapshot: Optional[Any] = None
    resolved_snapshot_path: Optional[Path] = None
    if snapshot_path is not None:
        snapshot = UnifiedSnapshot.load(snapshot_path, silent=True)
        if snapshot is None:
            raise ValueError(f"Snapshot could not be loaded: {snapshot_path}")
        resolved_snapshot_path = snapshot_path
    else:
        search_paths: list[Path] = []
        if resolved_data_dir is not None:
            search_paths.append(Path(resolved_data_dir))
        rd = data_cfg.get("raw_data_dir")
        if isinstance(rd, str) and rd.strip():
            search_paths.append(Path(rd))
        if search_paths:
            snapshot = find_unified_snapshot(search_paths, run_id=run_id, logger=None)
            if snapshot is not None:
                rid = getattr(snapshot, "run_id", None)
                if isinstance(rid, str) and rid.strip():
                    for base in search_paths:
                        cand = base / f"snapshot_{rid}.json"
                        if cand.is_file():
                            resolved_snapshot_path = cand
                            break

    resolved_image_size = image_size if image_size is not None else data_cfg.get("image_size", 224)
    try:
        resolved_image_size = int(resolved_image_size)
    except (TypeError, ValueError):
        resolved_image_size = 224
    if resolved_image_size < 1:
        resolved_image_size = 224

    resolved_classes = list(class_names or [])
    if not resolved_classes:
        resolved_classes = _discover_class_names(resolved_data_dir)
    if not resolved_classes:
        cfg_classes = data_cfg.get("class_names")
        if isinstance(cfg_classes, list):
            resolved_classes = [str(x).strip() for x in cfg_classes if str(x).strip()]
    if not resolved_classes and snapshot is not None:
        resolved_classes = _discover_class_names_from_snapshot(snapshot)

    resolved_num_classes = int(num_classes) if num_classes is not None else None
    if resolved_num_classes is None and resolved_classes:
        resolved_num_classes = len(resolved_classes)

    effective_run_id = run_id
    if not effective_run_id and snapshot is not None:
        snap_rid = getattr(snapshot, "run_id", None)
        if isinstance(snap_rid, str) and snap_rid.strip():
            effective_run_id = snap_rid

    snapshot_info = _snapshot_summary(snapshot) if snapshot is not None else None

    manifest = {
        "schema_version": 1,
        "created_at": datetime.now(timezone.utc).isoformat(),
        "export": {
            "command": "mb export bundle",
            "run_id": effective_run_id,
            "snapshot_path": str(resolved_snapshot_path) if resolved_snapshot_path is not None else None,
        },
        "model": {
            "framework": "pytorch",
            "weights_format": "safetensors",
            "architecture": resolved_architecture,
            "num_classes": resolved_num_classes,
            "class_names": resolved_classes or None,
        },
        "preprocessing": {
            "image_size": int(resolved_image_size),
            "channels": 3,
            "normalize_mean": [0.485, 0.456, 0.406],
            "normalize_std": [0.229, 0.224, 0.225],
        },
        "source_context": {
            "pipeline_model_defaults": {
                "default_framework": model_cfg.get("default_framework"),
                "default_architecture": model_cfg.get("default_architecture"),
            },
            "pipeline_data_defaults": {
                "data_dir": data_cfg.get("data_dir"),
                "raw_data_dir": data_cfg.get("raw_data_dir"),
                "image_size": data_cfg.get("image_size"),
                "class_names": data_cfg.get("class_names"),
            },
            "snapshot": snapshot_info,
        },
        "artifacts": {
            "weights_file": weights_path.name,
            "weights_sha256": _sha256_file(weights_path),
            "weights_size_bytes": weights_path.stat().st_size,
            "architecture_file": arch_py_path.name if include_architecture_py else None,
        },
    }
    manifest_path.write_text(json.dumps(manifest, indent=2), encoding="utf-8")

    if include_architecture_py:
        arch_py_path.write_text(
            _architecture_stub_text(
                architecture=resolved_architecture,
                num_classes=resolved_num_classes,
                framework="pytorch",
            ),
            encoding="utf-8",
        )
        if not arch_py_path.is_file():
            raise RuntimeError("Requested model_architecture.py but file was not created")

    return {
        "weights_path": str(weights_path),
        "manifest_path": str(manifest_path),
        "architecture_path": str(arch_py_path) if include_architecture_py else None,
    }

